### ISSUE TITLE
The MessageHeaderAnalyzer only shows up for messages in the primary Exchange mailbox

### ISSUE THREAD

**Issue by lathans** [microsoft/MHA#10]
I can see the MessageHeaderAnalyzer for messages in my primary Exchange mailbox.

Other add-ins like the "Unsubscribe" add-in shows up for other mailboxes I access in my Office 365 Exchange Online environment like shared mailboxes and directly set up Exchange accounts.

However, MessageHeaderAnalyzer is nowhere to be seen when I look at shared mailboxes or secondary Exchange accounts.

It is the same both for local Outlook 2016 and for OWA.

Any suggestions? Thanks! :)

**Comment by stephenegriffin** [comment]
I don't get to control where it shows up, but I did just update it today to support command buttons in the ribbon. Does that allow it to now work in the other mailboxes?

**Comment by stephenegriffin** [comment]
Also, did you install it for those other mailboxes?

**Comment by lathans** [comment]
Hi and thanks for the reply!

 

Today I cannot see MessageHeaderAnalyzer anywhere in my desktop Outlook 2016 (Windows) client. I tried to add it to the buttons in the ribbon, but I cannot see any trace of MHA in my Outlook. Maybe I’m not looking for the right thing or in the right place. Other add-ins like Unsubscribe, Bing Maps and Action items still shows up for all my mailboxes in my Outlook client.

 

If I now look in OWA I can see a new little blue MHA-button which shows me headers with a new layout. The gray line with MessageHeaderAnalyzer that was previously on top of the messages is no longer to be seen.

 

I have installed it for all my mailboxes that I can log into, but I don’t see how I can manage addons for shared mailboxes. It also don’t show up in OWA if I open another mailbox than the one that I am logged in as, even though if both my own and the other mailbox has MHA installed.

 

-- 

Best regards

Thomas Andersen

**Comment by stephenegriffin** [comment]
> If I now look in OWA I can see a new little blue MHA-button which shows me headers with a new layout. The gray line with MessageHeaderAnalyzer that was previously on top of the messages is no longer to be seen.

That's the new command bar UI, which was mandated to stay in the store.

**Comment by lathans** [comment]
That's fine, but is it still possible to use MHA in the desktop Outlook 2016 client on Windows? Are there any information on this? Thanks.

**Comment by stephenegriffin** [comment]
It works for me, so yes, you should be able to use it. We just republished the manifest a couple days ago, which is likely part of the problem. Could you try removing the addin and re-adding it from the store?

**Comment by lathans** [comment]
Today I saw the MHA button in the ribbon before doing anything. After changing between some folders I did not see it again before removing the addin and adding it again from the store.

First I only saw it for my primary account and not any other mailboxes. After just clicking around a bit in Outlook it showed up in the other mailboxes as well.

I've tried restarting Outlook to reproduce the problem and the MHA button was gone again, and may suddenly appear, and may suddenly go away again, all in just a few minutes after starting Outlook. While writing the previous sentence I could not see the button. After switching back to Outlook the button was there again, but only for two out of three mailboxes. And now, two seconds after, I cannot see the button in any of the mailboxes, and even while clicking around for several minutes I still don't see it.

I tried again to restart Outlook and the icon appeared after a few seconds, only to disappear again after changing folders and I currently see it in one of my secondary mailboxes, but not the others. A few seconds later I now see it on both my secondary mailboxes, but not my primary. It has now been like this for several minutes.

Sorry for not giving any better explanation of the problem, but it seems too variable or random for me to describe it any better, but something is clearly not working as intended here.

Please tell if there is anything I can do to help resolve this issue.

-- 
Best regards
Thomas Andersen

**Comment by stephenegriffin** [comment]
It sounds like the issue you're having is with Outlook, not the add-in. Nothing in my code is involved in deciding when to display the button. That's all Outlook.
