### ISSUE TITLE
Not working as expected on Win10

### ISSUE THREAD

**Issue by ReeveF** [microsoft/MHA#105]
This app is highly useful but appears to work only on true Exchange accounts ("@outlook.com") and not on POP3's.  This is the reason app didn't appear in Outlook's list of add-in's; I had to sign into outlook.com directly and disable the add-in there.

Specific issue: Outlook 2016 crashed when I did an email search on all folders with "read:no".

**Comment by stephenegriffin** [comment]
What version of Outlook? Also - is the issue that the add-in doesn't appear or that Outlook crashes? Or are you reporting two unrelated issues?

**Comment by ReeveF** [comment]
Current Outlook (2016) and up to date with Microsoft fixes.

Not appearing in the client Outlook list of add-in’s appears to be standard behavior based on a quick search on add-in’s.  It’s not a problem, just an unplanned learning experience.

-Reeve

**Comment by stephenegriffin** [comment]
Ok - so are you currently experiencing an issue with MHA?
