### ISSUE TITLE
Cannot use MHA in outlook 2016

### ISSUE THREAD

**Issue by fatman1501** [microsoft/MHA#11]
![image](https://cloud.githubusercontent.com/assets/26477655/24031967/69e35ca6-0b20-11e7-8a8b-1a07ac12561d.png)

**Comment by skipdog77** [comment]
I have the same issue in Outlook 2016.  but also in OWA -- it has the same exact issue.  Perhaps the later CUs broke?  Would love to see this fixed - awesome plugin..

**Comment by mattzuba** [comment]
Adding a 'me too' to this...

**Comment by davidmi711** [comment]
Hopping on the "Me too" band wagon...

**Comment by Clayo84** [comment]
I've submitted a case to Microsoft Premier Support on this issue as well. 117031715472502 incase anyone stumbles across this and wants something to reference.

**Comment by stephenegriffin** [comment]
Can I get build numbers from some clients that don't work?

**Comment by stephenegriffin** [comment]
Also - can people who repro this try hitting this url?
http://mha.azurewebsites.net/pages/desktoppane.html

It should render the top line of MHA and react to hover.

**Comment by mattzuba** [comment]
I am able to hit the website above, not sure how to find the build number, but the version on the OUTLOOK.EXE executable is 16.0.4498.1000

**Comment by stephenegriffin** [comment]
@mattzuba https://www.slipstick.com/outlook/outlook-version-numbers/
https://support.microsoft.com/en-us/help/3141511/february-7-2017-update-for-outlook-2016-kb3141511
Looks like MSI for you.

Was mha offered to you via the old gray bar or the new ribbon button? If you right click on the failed render do you get a context menu? If so, is there a security information option? If so, does it give you a URL? What URL does it give?

**Comment by skipdog77** [comment]
MHA is now rendering with new ribbon button in Outlook 2016. The URL you posted -- comes back with "Error 403 - This web app is stopped."  Outlook 2016 version is 16.0.4498.1000 (32bit)

in OWA - it looks like rendering looks like the old style.  The error in OWA is "App Error Something went wrong and we couldn't start this app.  Please try again later or contact your system administrator."

(edited to fix OWA error and display)

![image](https://cloud.githubusercontent.com/assets/25821772/24073003/6fe6cbc8-0bc6-11e7-8895-41dc9d3ed4f3.png)

**Comment by Clayo84** [comment]
I updated the version installed in my tenant to 3.0 of the MHA, but it is still failing.

Outlook 2016 version 1701 build 7766.2060
Same error in OWA.

**Comment by stephenegriffin** [comment]
@skipdog77 it looks like I've hit my data cap, someone I've never come close to doing before. I'll have to investigate why.

**Comment by stephenegriffin** [comment]
I've upgraded my plan on azure (I had some cap remaining in my subscription) and restarted the app, so the 403 should be gone. Is anyone still seeing a problem loading MHA and if so, please give me some details so I can track down where the problem is:
1 - Outlook version (C2R or MSI, build number && fork if C2R)
2 - MHA showed as grey bar or ribbon button
3 - When MHA failed to load, what URL does right click show you were trying to hit.
4 - If you can get the URL from 3, what do you see from a browser when you hit that same URL?

We'll get to the bottom of this. Thanks for bearing with me.

**Comment by skipdog77** [comment]
Stephen - bravo.  Working for me now.

**Comment by stephenegriffin** [comment]
@skipdog77 great to hear. I suspect there's another issue some of the others are facing. We'll see if further reports come in.

**Comment by fatman1501** [comment]
it works now!

**Comment by Clayo84** [comment]
@stephenegriffin It's working for me now. I'm waiting for confirmation from my end users as well. I'll let you know when that comes in.

**Comment by davidmi711** [comment]
It is working now in both Outlook 2016 and outlook.office365.com. Thank you! I don't realize how much I use something until it does not work :)

**Comment by Clayo84** [comment]
Yes, it is working again for my folks here at Cornell as well. I will get the MS case closed.

**Comment by stephenegriffin** [comment]
Thanks for the reports. I didn't know how much this was being used. It's more of a toy/learning project for me.
