### ISSUE TITLE
Unable to run add-in in Outlook

### ISSUE THREAD

**Issue by AndyH16** [microsoft/MHA#115]
I'm getting an error everytime I try to run the MHA within Outlook (Office 365 Insider), I am able to run it through https://outlook.office.com

It just one day suddenly stopped working, I'm not sure if this was down to a 365 update or something else.

I've attached a screenshot of the issue. Reinstalling doesn't seem to work and the add-in has been installed via the organization section of Exchange Online.

![MHA-Error](https://user-images.githubusercontent.com/38286177/61945761-b8b0e000-af98-11e9-8634-7583482cd09d.png)

**Comment by stephenegriffin** [comment]
Odd - it's still working for me. What version do you see in File/Office Account in the About Outlook section?

**Comment by AndyH16** [comment]
It's 1908 (11916.20000), though I believe it's been happening since 1904 or 1906 for me. I'm not sure if there's some sort of cache somewhere that might need clearing, as it's obviously working for others. But I have seen other post in the reviews section of the add-in store with the same error.

**Comment by compkickers** [comment]
Ive got the same problem with my addon it was working fine till recently??
Is there a solution yet.

**Comment by AndyH16** [comment]
I created a test VM off our domain and the plugin works from there. I haven't had a chance to try joining the PC to the domain yet to see if it suddenly stops working.

**Comment by AndyH16** [comment]
...typically as I posted that I had a brainwave and it's fixed it.

The culprit was Applocker, it seems either Office 365 or Windows 10 1903 has added the need for another package to be whitelisted in order to run, 'Microsoft.Win32WebViewHost'.

**Comment by mmahacek** [comment]
Any idea on this one if we aren't using Applocker?

**Comment by AndyH16** [comment]
Do you get any events logged in the Application or System log around the same time? Maybe if 'Microsoft.Win32WebViewHost' was causing this issue for me (by being prevented from running). It may need reinstalling on your PC? Looking on Microsoft's site the app package is part of Edge.

> Get-AppxPackage -AllUsers "Microsoft.Win32WebViewHost" | foreach {Add-AppPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

I could be wrong but maybe it's worth a try.

**Comment by mmahacek** [comment]
That command didn't fix it.  I'll keep looking.
