### ISSUE TITLE
iPad IOS not recognised 

### ISSUE THREAD

**Issue by dougal-aus** [microsoft/MHA#118]
When looking at the email headers,I got the following:

MOBILE DIFFERENTIATION PAGE

If you see this page something has gone wrong. Please open an issue at https://github.com/stephenegriffin/mha and include the diagnostics below.

Diagnostics

User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)
iOS (Framework7 check): false
iOS (userAgent check): 
iPad: false
iPhone: false
Android: false

<img width="441" alt="Screenshot 2019-10-18 at 7 18 07 am" src="https://user-images.githubusercontent.com/56699650/67044288-a7323b00-f177-11e9-89d0-6df8b80460b2.png">

**Comment by stephenegriffin** [comment]
Can you clarify if this is the Outlook App or OWA?

**Comment by dougal-aus** [comment]
Outlook app on the iPad but the outlook app is working on the iPhone!

--
Dougal Everingham
+61 431 475 606
Sent from my iPhone

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by stephenegriffin** [comment]
Hrmm - I set up Outlook on on ipad but it won't show me MHA at all :( I can see it in OWA and on the Outlook app on the iPhone.
**edit** - got it running and see issue

**Comment by stephenegriffin** [comment]
Fixed by 0309b8415c88f0a928a1235321bd2fe9fe3c359e
