### ISSUE TITLE
Unable to use MHA to view headers of a eml or msg attachment.

### ISSUE THREAD

**Issue by mcvic1rj** [microsoft/MHA#12]

**Comment by stephenegriffin** [comment]
I did some quick testing and it looks like the command bar button doesn't even light up, meaning that nothing in my code is yet running. So this isn't a bug in MHA. You might want to consider raising an issue over on https://github.com/OfficeDev/office-store-docs that they need to be clearer about when/where add-ins can be activated.

**Comment by mcvic1rj** [comment]
Thank you for the update. I have raised an issue in the office store docs repo.
