### ISSUE TITLE
Security: Cross site scripting (XSS) Vulnerability

### ISSUE THREAD

**Issue by n0n4me403** [microsoft/MHA#126]
Hi,

I would like to report a XSS vulnerability. 

Vulnerable code:
https://github.com/stephenegriffin/MHA/blob/master/Scripts/Headers.js#L143

payload:
`X-Forefront-Antispam-Report:
 CIP:54.240.11.65<img src=x onerror=alert(1)>;`

**Comment by stephenegriffin** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

**Comment by stephenegriffin** [comment]
@n0n4me403 - thanks for finding that - mind if I ask how you pinpointed that? I'd love any insights you have on how I can scan the rest of the codebase for similar issues.

**Comment by n0n4me403** [comment]
Hi @stephenegriffin, 

Actually I fuzzed it and manually review js code.

**Comment by stephenegriffin** [comment]
Awesome. Lemme know if you find anything else suspect. Thanks again!
