### ISSUE TITLE
MHA great on laptop, but doesn't work on any of my desktop PCs

### ISSUE THREAD

**Issue by Tolqua** [microsoft/MHA#13]
Installed and visible in all Outlook clients, but only works on my laptop - on all three desktop PCs the MHA window just displays 'Message Header Analyzer' with a partial rendering of what should be visible in the area immediately below (or nothing at all).  Here's a screen clip:

![mha failure](https://user-images.githubusercontent.com/30085523/28082207-b8d3072c-6669-11e7-96d4-89f631663e8b.PNG)

...and no header info.
This is a real pity because it'd be a real time-saver if it worked on the machines I need it to.
Hope you can help.
I'm running Windows Pro 32 (1703) with Firefox 54.0.1

**Comment by stephenegriffin** [comment]
What version of Outlook are you running on each machine?

**Comment by Tolqua** [comment]
All are the latest Office 365 ProPlus version, 1701 (Build 7766.2092).

All OSs are Windows 10 (1703) 64 bit, fully updated (sorry for error in previuos post).  The only difference I can see is that the laptop (Dell XPS13) on which MHA is working fine is running Home rather than the Pro versions installed on the desktop PCs.

**Comment by Tolqua** [comment]
Just updated all machines to Office 365 ProPlus version, 1701 (Build 7766.2099) and the situation's unchanged: still fine on XPS13, but not working on any desktop install.

**Comment by stephenegriffin** [comment]
Do any other add-ins work on the desktops?

**Comment by Tolqua** [comment]
The only other add-in I 'use' and can see working is the MS Outlook Junk Email reporting tool which is installed on one PC (where MHA fails) and it works fine.

**Comment by stephenegriffin** [comment]
If this still repros with current Outlook and rewritten UI, please log a new bug
