### ISSUE TITLE
Error while parsing the 'sandbox' attribute: 'ms-allow-popups' is an invalid sandbox flag. On-Premises Exchange 2013

### ISSUE THREAD

**Issue by t3easy** [microsoft/MHA#134]
After the installation in the On-Premises Exchange 2013 CU 23 with latest security patch I try to analyse headers and get the error:
![Bildschirmfoto 2019-12-06 um 22 07 49](https://user-images.githubusercontent.com/3628035/70356670-3228db00-1875-11ea-959f-fff82952600e.png)
![Bildschirmfoto 2019-12-06 um 22 10 40](https://user-images.githubusercontent.com/3628035/70356704-453bab00-1875-11ea-8818-d6f1e0e20a79.png)

I haven't tried the add-on before.

**Comment by stephenegriffin** [comment]
Do other add-ins work?

**Comment by t3easy** [comment]
The default Bing Maps works in OWA.
And MHA works fine in Outlook but not in OWA.

**Comment by stephenegriffin** [comment]
nothing in that stack looks like my stuff - it looks like OWA trying to parse a manifest. Does network show anything touching https://mha.azurewebsites.net? Besides maybe the icon load?
