### ISSUE TITLE
How to start locally

### ISSUE THREAD

**Issue by courtenayparserr** [microsoft/MHA#143]
Hi @stephenegriffin 

Curious how we start the web server locally for testing?

Ive done an npm install and got all the packages. Npm start doesnt run anything though?

![image](https://user-images.githubusercontent.com/24819057/75768231-0fd12b80-5d98-11ea-9c81-0a109ed182e5.png)

**Comment by stephenegriffin** [comment]
I just run the project in visual studio. If you wanna send a PR for adding a start script I can consider it.

**Comment by courtenayparserr** [comment]
All good @stephenegriffin. Im not sure how you run it locally? Isn't everything served from here anyway: https://mha.azurewebsites.net?

Or do you have a way of hosting it locally?

When i try run in visual studio, it first creates a "web.config" and then I get this:

![image](https://user-images.githubusercontent.com/24819057/75835881-3c2a8d80-5e14-11ea-83d0-d0b1a6295b07.png)

**Comment by stephenegriffin** [comment]
As far as I know, I have it running in IIE express locally:
![image](https://user-images.githubusercontent.com/6773183/75921805-c7fde300-5e2f-11ea-8ee1-bcf7eafc7f57.png)
The error you're seeing says you don't have a default document - I usually set Pages\mha.html or Pages\unittests.html depending on what I'm working on. Note that neither of these are in the repo to start - they're built via the build script.

**Comment by courtenayparserr** [comment]
Thanks @stephenegriffin!

Last question: How do you debug? As in how do you run that local copy within Outlook?

**Comment by stephenegriffin** [comment]
1. Make a copy of the manifest.xml
1. Edit this copy to give a new DisplayName and Id (any random guid will work)
1. Change all the URLs. Instead of mha.azurewebsites.net, refer to localhost:44358 (use whatever port you're running on)
1. In Outlook/OWA, add a new add-in and select this manifest.

BTW - I welcome any pull request you wanna offer to make it easier for others to onboard on the project.
