### ISSUE TITLE
Link to `Archived-At` value

### ISSUE THREAD

**Issue by BigBlueHat** [microsoft/MHA#144]
Group mailing lists often include a URL to a location on the Web for (typically publicly) viewing a mailing list post.

The header is defined in https://tools.ietf.org/html/rfc5064

The header (and its value) show up in the "Other" tab in MHA, but getting to it, copying it out, and putting it to use in a browser (or email to someone else) is super tedious.

Would it be possible to surface this "actionable" bit of info either sooner in the UX in MHA or in it's own button/context menu item?

I've poked around in the code a bit, but haven't seen a clear route to providing a PR for this...would be happy to with some pointers! 😃 

Thanks!
🎩

**Comment by stephenegriffin** [comment]
In Summary.js you'd want to add a row to summaryRows, with a corresponding update to the string table
