### ISSUE TITLE
Outlook iOS - EWS callback failed

### ISSUE THREAD

**Issue by hericius** [microsoft/MHA#146]
Hello,

I installed morning your add-in MHA on my Exchange/O365 and on my Outlook app on my Windows 10 Pro without issues.  MHA is working fine on Windows 10.

I'm using too Outlook on iOS devices, iPhone and iPad.  I encountered the following issue when I ask MHA to analyze the header of a email: EWS callback failed.

I tried to disable/enable the addin, same issue.
Restart the device, same issue.

What can I do?

Regards,
André,

**Comment by stephenegriffin** [comment]
Click the gear icon to show the settings window, then click diagnostics. Could you copy what shows there and paste it here?

**Comment by hericius** [comment]
Hello Stephen,

Sorry, but I can’t help you.
I discovered your Outlook add-in few days before switching from Windows to MacOS, and I’m now using Mail from Apple.

Stay safe,

André,

On 27 Mar 2020, at 16:04, Stephen Griffin <notifications@github.com<mailto:notifications@github.com>> wrote:



Click the gear icon to show the settings window, then click diagnostics. Could you copy what shows there and paste it here?
