### ISSUE TITLE
Ews call back failure on iOS outlook addin 

### ISSUE THREAD

**Issue by bakerm00** [microsoft/MHA#147]
Opening mHA to check a header in outlook iOS 
![45FD9EC2-40DB-4C6A-9780-2EDA32664A69](https://user-images.githubusercontent.com/38048919/78398990-fcf68480-75eb-11ea-9cec-9969b04f9a62.png)
![468D7E07-2435-4DC0-8BE7-AFA2929A3B0D](https://user-images.githubusercontent.com/38048919/78399015-0a137380-75ec-11ea-943c-4fa84e1a79bb.png)

Diagnostic log
User Agent = Outlook-iOS/723.4216190.prod.iphone (4.31.0)
Requirement set = 1.5
ui = new-mobile
Last Update = Thu, 06 Feb 2020 16:21:45 GMT
contentLanguage = en-GB
displayLanguage = en-GB
hostname = OutlookIOS
hostVersion = 4.31.0.0
Office.context.mailbox._initialData$p$0 = missing
origin = https://mha.azurewebsites.net
path = /pages/parentframe.html
API used = EWS
itemId = true
itemType = message
itemClass = IPM.Note
ERROR: Async Response
{
  "status": "succeeded"
}
{anonymous}()@https://mha.azurewebsites.net/Scripts/22d4f0b6a/GetHeadersEWS.js:79:31
mailbox.makeEwsRequestAsync()@https://mha.azurewebsites.net/Scripts/22d4f0b6a/GetHeadersEWS.js:46:28
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:7738:17
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:7487:23
agaveResponseCallback()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4269:42
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4155:57
agaveHostCallback()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4091:46
{anonymous}()@https://mha.azurewebsites.net/pages/parentframe.html?default=new-mobile:1:50
global code()@https://mha.azurewebsites.net/pages/parentframe.html?default=new-mobile:1:90
ERROR: EWS callback failed : Failed to retrieve headers.
mhaStrings()@https://mha.azurewebsites.net/Scripts/22d4f0b6a/GetHeadersEWS.js:74:36
mailbox.makeEwsRequestAsync()@https://mha.azurewebsites.net/Scripts/22d4f0b6a/GetHeadersEWS.js:46:28
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:7738:17
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:7487:23
agaveResponseCallback()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4269:42
{anonymous}()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4155:57
agaveHostCallback()@https://appsforoffice.microsoft.com/lib/1/hosted/outlook-ios-16.00.debug.js:4091:46
{anonymous}()@https://mha.azurewebsites.net/pages/parentframe.html?default=new-mobile:1:50
global code()@https://mha.azurewebsites.net/pages/parentframe.html?default=new-mobile:1:90

**Comment by stephenegriffin** [comment]
I repro this, but nothing changed in my app - must be server or client that changed - will investigate

**Comment by stephenegriffin** [comment]
Basically, the callback for makeEwsRequestAsync returns {"status": "succeeded"} and nothing else.

**Comment by stephenegriffin** [comment]
Fixed by 3c7bb992019c873fa899c5532ccbd9b088b29518
