### ISSUE TITLE
Create Android UI

### ISSUE THREAD

**Issue by stephenegriffin** [microsoft/MHA#15]
Should be based on the apple UI, but done the android way.

**Comment by mitchcapper** [comment]
Given the cross-plat support for android outlook what is required for this as from the docs I was assuming there were not android specific requirements? Would be happy to work on it.

**Comment by stephenegriffin** [comment]
I honestly don’t know. Maybe the iOS page would work fine on android and look right for android. But since I don’t have access to any android devices, I can’t test this.

**Comment by stephenegriffin** [comment]
Here's one page which highlights design differences for Android vs iOS:
https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design

**Comment by mitchcapper** [comment]
Sorry I missed the response on this.  I am happy to get it working for android but I am missing what is required to enable it to show up on android.  It auto-populates as an outlook for desktop addin but not in the same exchange account on mobile.  I am not sure how to test:)

**Comment by stephenegriffin** [comment]
Does this help any?
https://www.microsoft.com/en-us/microsoft-365/blog/2017/09/08/your-favorite-apps-now-in-outlook-on-android/

**Comment by stephenegriffin** [comment]
oh - and when you actually get it enabled, MHA might still check if we're on android and complain - you'd have to find and remove that too. But first you gotta get outlook for android to recognize the app at all...

**Comment by stephenegriffin** [comment]
looks like VS has an android emulator - use this to set up a test environment

**Comment by Rathna-K** [comment]
would love Android support. I can help with any testing etc. let me know!

**Comment by stephenegriffin** [comment]
fixed by #369
