### ISSUE TITLE
Decoding failure

### ISSUE THREAD

**Issue by szepeviktor** [microsoft/MHA#16]
Summary shows the subject is
`Ãj fiÃ³k megerÅsÃ­tÃ©s TÃ¶rÃ¶lj ki kÃ©rlek TÃ¶rlendÅ rÃ©szÃ©re`

Source
```
Subject: =?utf-8?B?w5pqIGZpw7NrIG1lZ2VyxZFzw610w6lzIFTDtnLDtmxqIGtpIGvDqXJsZWsgVMO2cmxlbmTFkSByw6lzesOpcmU=?=
```

Please advise.

on https://outlook.live.com/owa/

**Comment by stephenegriffin** [comment]
Do you have what OWA shows the subject as?

**Comment by szepeviktor** [comment]
The decoded subject.

> Subject: Új fiók megerősítés Törölj ki kérlek Törlendő részére

**Comment by stephenegriffin** [comment]
Thanks - got this working - doing more test cases now - how to check in soon

**Comment by stephenegriffin** [comment]
Fixed by 053af2ca57af9057b99cf106f99b29bfe7393688

**Comment by szepeviktor** [comment]
What a big commit! 

Thank you. 

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
