### ISSUE TITLE
Website issue: No action when clicking Analyze

### ISSUE THREAD

**Issue by zerodrool** [microsoft/MHA#161]
No action occurs when attempting to analyze header. 
at mha.azurewebsites.net

**Comment by ekinnee** [comment]
She's dead Jim.

**Comment by click3rs** [comment]
Same. 
No actions after push the button. 
Tested on : https://mha.azurewebsites.net/ and https://mha.azurewebsites.net/pages/mha.html using Edge, Chrome and IE. 
Site still opening just the button is not working.

**Comment by babybirdhome** [comment]
Same issue. No time to troubleshoot, unfortunately.

**Comment by babybirdhome** [comment]
Console errors from incognito mode where I'm not blocking anything for diagnosis.

![image](https://user-images.githubusercontent.com/68442272/87820641-45e0ea80-c823-11ea-88c6-d2175418c55d.png)

**Comment by babybirdhome** [comment]
Issue is resolved for me as of new commit 1 hour ago. Thank you, sir!

**Comment by stephenegriffin** [comment]
Sorry. Bad checkin

**Comment by stephenegriffin** [comment]
postmortem - this was a minifying failure - I've taken steps to ensure these are caught client side during dev/test so they don't mae it to production
