### ISSUE TITLE
Enhancement Request:  support for Shared Mailboxes

### ISSUE THREAD

**Issue by booklegger** [microsoft/MHA#17]
MHA is proving very useful for Incident Response teams.  It would be terrific if **MHA worked with Shared Mailboxes**.  Proposed use-case:  potential phishing messages are redirected to a shared mailbox. Admins log into the Shared Mailbox to triage messages, confirm they are phishing attacks, and inspect the message headers for useful detection data.

**Comment by stephenegriffin** [comment]
AFAIK, I have no control over where my add-in is enabled. Do you have other add-in which light up in a shared mailbox?

**Comment by meixger** [comment]
https://officespdev.uservoice.com/forums/224641-general/suggestions/11634318-support-for-shared-mailboxes
