### ISSUE TITLE
The operation failed

### ISSUE THREAD

**Issue by skipdog77** [microsoft/MHA#18]
Hi Stephen.  Great plugin!

Mine has been erroring out on every system with "The operation failed"

Have you seen this reported? Any ideas?  Outlook 2016 running on Exchange 2016 server.

**Comment by stephenegriffin** [comment]
It's working for me - still failing for you?

**Comment by skipdog77** [comment]
Stephen - every single time, from home, work, Mac, PC.. Doesn't matter.  From OWA.  

"The Operation Failed"

Co-worker also experiencing the issue (we use it a lot!)

Can I grab logs for you?

**Comment by mdima** [comment]
Same here... "The Operation Failed", the only information more I can give more is the "Diagnostic" result:

Requirement set = 1.5
hostname = Outlook
hostVersion = 16.0.8528.2147
itemType = message
contentLanguage = it-IT
displayLanguage = en-US
touchEnabled = 0

Thanks,
Michele

**Comment by stephenegriffin** [comment]
Forgot to ask: do other apps work? Or is it just MHA that fails?

Could you check your protected mode settings? As spelled out here: https://support.microsoft.com/en-us/help/2761180/apps-for-office-don-t-start-if-you-disable-protected-mode-for-the-rest

**Comment by luisjmoreno** [comment]
Hello Stephen, 
I believe I am having the same issue but slightly different. MHA works well on Outlook for Windows and Mac. However, It does not work on OWA on any browser. I tried removing it and adding it again, didn't help. I had it working for Exchange 2013 CU14 and two days ago just upgraded to CU18.  
This is what I get after I hit the button Message Header Analyzer within OWA. 

Message Header Analyzer

The remote server returned an error: (404) Not Found.

Diagnostics
Requirement set = 1.3
hostname = OutlookWebApp
hostVersion = 15.0.1347.2
OWAView = ThreeColumns
itemType = message
contentLanguage = 
displayLanguage = en-US
touchEnabled = undefined

**Comment by Vierxa** [comment]
Hello Stephen,

I exerience the same issue.
![image](https://user-images.githubusercontent.com/36500601/36247894-e75ce784-1235-11e8-963a-49e11e361309.png)

Thanks for helping me.

**Comment by stephenegriffin** [comment]
Since this is OWA, you can use F12 debugging to watch the requests. The first request we'll make is for GetClientAccessToken. So you can check if you got back a token or an error from that. If that worked, we then make a request for the transport header. The request URL will look like this:
https://outlook.office365.com/api/v2.0/me/messages/<id>?$select=SingleValueExtendedProperties&$expand=SingleValueExtendedProperties($filter=PropertyId eq 'String 0x007D')

I presume one of these two calls is the one that failed.

**Comment by Vierxa** [comment]
Hi Stephen,

Please find the error.
The URL is not outlook.office365.com because we have on-premises servers.

Regards,

![image](https://user-images.githubusercontent.com/36500601/36727851-0dec61ee-1bbf-11e8-8567-e566cf605ad0.png)

**Comment by luisjmoreno** [comment]
Hi Stephen, 
Bad news, I noticed a new change on the MHA version. Unfortunately, this new version broke everywhere in all my devices Mac, Windows and Internet Browsers. MHA doesn't work on any browser or email client such as Outlook for Windows or Mac. 

Before this new version / change, MHC was working only on Outlook for Windows. Now, when I run MHA on an email on Windows, I get a message that says "Failed to retrieve headers". I have removed  and re-added the app and still does not work.  

- Screen shot in Outlook for Mac
![outlookformac](https://user-images.githubusercontent.com/33647149/36743290-e90e145a-1bb7-11e8-82c4-18153e408486.png)

- Screen shot in Outlook for Windows
<img width="351" alt="outlookforwindows" src="https://user-images.githubusercontent.com/33647149/36743531-81e56106-1bb8-11e8-8ae8-2e1f29922fea.png">

- Screen shot within OWA using Google Chrome (same results within other browsers, including IE)
<img width="639" alt="owa" src="https://user-images.githubusercontent.com/33647149/36743356-1cc48a86-1bb8-11e8-90dc-de0275bd366d.png">

We are running Exchange 2013 CU18 on premises. I have a different email on Outlook.com where I use MHA too and it works there. Please help!!

**Comment by stephenegriffin** [comment]
Closing this bug because it has become a bucket where all sorts of issues are posted. Please post different issues in different bugs!

**Comment by stephenegriffin** [comment]
@luisjmoreno @Vierxa - I've closed this bug because it has become a pool of random issues. If you're still seeing a problem, please post a new bug. Do not post your issue on someone else's bug unless you have good reason to believe you are seeing the exact same issue. Otherwise it's really hard to sort out who's talking about what.
