### ISSUE TITLE
Header name X-Forefront-Antispam-Report is replaced with CIP

### ISSUE THREAD

**Issue by vilega** [microsoft/MHA#194]
Parsing EXO headers will add CIP as header and X-Forefront-Antispam-Report header name is missing .
CIP is not the header name.
Who is looking/searching directly for this might be distracted
![image](https://user-images.githubusercontent.com/38977389/90612387-9f687a80-e210-11ea-9798-003b33c3025b.png)
![image](https://user-images.githubusercontent.com/38977389/90612420-aabba600-e210-11ea-8138-24530c3b0e52.png)

**Comment by stephenegriffin** [comment]
Can you paste in text a set of headers which reproduce this? I didn't repro with my attempt.

**Comment by vilega** [comment]
yesterday it worked with any header.

Today tested with some and the behavior is:
- X-Forefront-Antispam-Report is not shown anymore in "Other headers", but listed as source header see bellow:
![image](https://user-images.githubusercontent.com/38977389/90759049-91862880-e2e8-11ea-9f98-c80284939944.png)
- so today that CIP instead of X-Forefront-Antispam-Report is not anymore in the other headers, but the header itself is named "source header"

**Is this expected new design change? Any reasons to do this?
Shouldn't be kept as "X-Forefront-Antispam-Report" in "Other headers"?**

Attached the header from last test.
[test header.txt](https://github.com/stephenegriffin/MHA/files/5102319/test.header.txt)

**Comment by vilega** [comment]
by the way: "X-Forefront-Antispam-Report-Untrusted" looks good under "other headers", only "X-Forefront-Antispam-Report" is affected
[test header2.txt](https://github.com/stephenegriffin/MHA/files/5102387/test.header2.txt)

**Comment by stephenegriffin** [comment]
I'm still not understanding what you're saying is wrong about how it's rendered.

> X-Forefront-Antispam-Report is not shown anymore in "Other headers", but listed as source header see bellow:

Yes - are you saying that's wrong?

> so today that CIP instead of X-Forefront-Antispam-Report is not anymore in the other headers, but the header itself is named "source header"

Yes - the contents of the X-Forefront-Antispam-Report header are the source for that section, so I included them verbatim as the source header. Are you saying that's wrong? Why do you call out that the header value start with CIP? Is that not correct?

> Is this expected new design change?

Not sure how to answer this. I mean - I wrote the code, so I guess I expected to do it? But if you're saying something is wrong about it I'd like to understand the issue before I commit to saying it's the expected design.

> Any reasons to do this?

I realized there were fields in the antispam reports that weren't getting parsed out. Some of them were documented, some weren't. The documented ones get parsed out and the remaining ones are unknown fields. In case anything about the parsing is wrong, I also show the original header untouched.

> Shouldn't be kept as "X-Forefront-Antispam-Report" in "Other headers"?

After the work I did on the antispam report parsing, the extra copy down in other headers became redundant, so I removed it. I did the same with the received headers, to, from, subject etc that all appear in their own sections. None of them belong in Other so I removed them. Are you saying this was the wrong choice?

**Comment by stephenegriffin** [comment]
Figured out what's going on. If you go look for message headers in OWA right now, all leading spaces are stripped. So while the header in proper RFC format should look like this:
![image](https://user-images.githubusercontent.com/6773183/90790763-6c88ba00-e2d6-11ea-9178-f7e51add20a2.png)
from OWA, it looked like this:
![image](https://user-images.githubusercontent.com/6773183/90790855-86c29800-e2d6-11ea-8b36-f5c8ee2ee41c.png)
with no leading spaces. To any header parser, this looks like a new header named CIP.

This is a bug in OWA that likely affects parsing of several headers. I'll have to see if I can do anything to handle this bad data better.

**Comment by stephenegriffin** [comment]
BTW - this only affects standalone with user supplied header text. Add-in pulls the headers itself and has no problem.

**Comment by abaerst** [comment]
Has there been any action on this item? I can concur that this is an issue when pulling the message header manually from OWA. Is there anything that I can do to rattle the cage for the OWA team on this? Has there been any acknowledgement or interest? Thanks.

**Comment by stephenegriffin** [comment]
>  Is there anything that I can do to rattle the cage for the OWA team on this?

You'd need to report the issue to the OWA team first.

**Comment by abaerst** [comment]
I opened a ticket in mid February through Office 365 Partner Support. It was eventually elevated to the product team. The product team hasn't officially reported back on the ticket yet, but according to my testing, message headers are now formatting correctly via OWA and can be parsed by MHA.
