### ISSUE TITLE
ADD-IN Error Outlook 2016 Desktop app

### ISSUE THREAD

**Issue by JackWent** [microsoft/MHA#20]
Hi,
Am I missing something? I have installed MHA and it works fine in OWA but in outlook 2016 (1801 Build 8828.2010) I get the following error.

ADD-IN Error
The Add-in could not be started. Close this dialog to ignore this problem or click "Restart" to try again.

No matter how many times i click restart nothing happens
![image](https://user-images.githubusercontent.com/19342915/33839988-925536ca-de8b-11e7-9a24-0bc1eef6d1ba.png)

Thanks

**Comment by stephenegriffin** [comment]
This is most likely an Outlook issue. Does Fiddler show any errors when trying to load the app? Do other apps have a problem loading?

**Comment by singhbrijraj** [comment]
Please refer https://support.microsoft.com/en-us/help/2761180/apps-for-office-don-t-start-if-you-disable-protected-mode-for-the-rest and see it that help.

Regards,

Brijs
