### ISSUE TITLE
Typescript errors when running deploy.cmd

### ISSUE THREAD

**Issue by stillcollating** [microsoft/MHA#234]
Not sure what I might have wrong.  Cloned the repo and ran deploy.cmd.  It looks like tsc isn't seeing any of the dependencies in node_modules.  They are present in  DEPLOYMENT_TARGET\node_modules.  Haven't made any changes.  Any thoughts?

`
5. Transpile TypeScript
src/Scripts/2047.ts:75:18 - error TS2552: Cannot find name 'cptable'. Did you mean 'Table'?

75         else if (cptable) {
                    ~~~~~~~

  src/Scripts/Table.ts:5:7
    5 const Table = (function () {
            ~~~~~
    'Table' is declared here.

src/Scripts/2047.ts:76:20 - error TS2552: Cannot find name 'cptable'. Did you mean 'Table'?

76             return cptable.utils.decode(getCodePage(charSet), hexArray);
                      ~~~~~~~

  src/Scripts/Table.ts:5:7
    5 const Table = (function () {
            ~~~~~
    'Table' is declared here.

src/Scripts/dates.ts:33:13 - error TS2304: Cannot find name 'moment'.

33         if (moment) {
               ~~~~~~

src/Scripts/dates.ts:35:24 - error TS2304: Cannot find name 'moment'.

35             let time = moment(date);
                          ~~~~~~
`

**Comment by stephenegriffin** [comment]
That's the KUDO deployment script for deploying on azure. What are you trying to accomplish? If you just want to test it out locally you can load the sln and run it from there. You might need the task runner explorer add-in.

**Comment by stephenegriffin** [comment]
Also - those errors are expected until I fully convert to typescript.

**Comment by stillcollating** [comment]
When I try to run locally, I don't have a Pages folder.  I don't see any other build scripts to run.  I'm in VS2017.

**Comment by stephenegriffin** [comment]
I use this to build - dunno if it supports 2017:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner

**Comment by stillcollating** [comment]
Oh.  I see now.  Thank you.   Is there a particular commit level I can go to that be similar to your current production release.  Pre-Typescript I guess.  I need a running version with code, so I can evaluate it for use in our organization.  Thanks again.

**Comment by stephenegriffin** [comment]
Master is production. Those typescript errors shouldn’t block generation of the js files

**Comment by stillcollating** [comment]
Thanks.  It looks like I was just missing the Scripts directory for it to copy the transpiled JS into.   However, now I seem to be missing aikey.js.  Is that something I'm supposed to generate?  

diag.min.js:294 GET http://localhost:55016/Scripts/aikey.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ diag.min.js:294

StandAlone.min.js:31 Uncaught ReferenceError: appInsights is not defined
    at HTMLButtonElement.analyze (StandAlone.min.js:31)

**Comment by stephenegriffin** [comment]
I don't share aikey.js because people kept downloading the source, running it locally, and polluting my telemetry. I wouldn't reject a pull request to make telemetry fails gracefully when the key isn't present.

**Comment by stephenegriffin** [comment]
I just pushed a fix for missing aikey.js

**Comment by stillcollating** [comment]
Thanks for all your help.  It's up and running now.  Is there way to test it with Outlook without pushing it through an Exchange server?  Everything I'm reading says it needs to be loaded through Exchange.

**Comment by stephenegriffin** [comment]
Is there some reason you don't just load it from [appsource](https://appsource.microsoft.com/en-us/product/office/WA104005406?src=office&corrid=08f3e7d5-b934-46c8-96bf-b58f6ceed044&omexanonuid=dc9f1943-a4d2-4142-873b-6188feea1609&referralurl=https%3a%2f%2fgithub.com%2fstephenegriffin%2fmha)?

If you're looking to dev on it, you'll want to build a local manifest and register that in Outlook. Start with the [manifest in the source](https://github.com/stephenegriffin/MHA/blob/master/Manifest.xml) and change all the URLs to point to localhost, using the port number configured in VS.

For instance, you'd change this:
` <IconUrl DefaultValue="https://mha.azurewebsites.net/resources/mhaLogo.jpg" />`
To this:
 ` <IconUrl DefaultValue="https://localhost:44358/resources/mhaLogo.jpg" />`
But your port # will likely be different.

**Comment by stillcollating** [comment]
I need to be able to build it for local deployment, and perhaps make modifications.  

I've made a local manifest.xml, but I don't know how to register it in Outlook 2016.

**Comment by stillcollating** [comment]
Nevermind.  I think I found the screen to add the manifest.xml.  Now I'm dealing with SSL issues.  But I'll try to work through it.

**Comment by stephenegriffin** [comment]
SSL: tell vs you want https. Outlook doesn’t like loading from http
