### ISSUE TITLE
After Office update, MHA will no longer open

### ISSUE THREAD

**Issue by pa-jberanek** [microsoft/MHA#241]
So, since a recent Office update, when I click on the MHA button I just get the error dialogue:

You can't use this add-in along with some of your COM add-ins. To continue, please try turning off your COM add-ins individually.

I'm not aware of having installed any COM add-ins recently.

Office: 2011 (Build 13426.20234 Click-to-Run)

**Comment by pa-jberanek** [comment]
So having said I installed said I'd not installed an COM add-ins recently, I just went to look at the add-ins, and saw the Sophos AV one...we just changed to Sophos recently...

https://i.imgur.com/2YsVfTr.png

**Comment by pa-jberanek** [comment]
Annoyingly, I can't simply disable it either, as "The add-in you have selected is enabled by your system administrator"

**Comment by stephenegriffin** [comment]
"You can't use this add-in along with some of your COM add-ins." I don't believe I've seen this particular error before...

**Comment by stephenegriffin** [comment]
Did some digging in the Outlook source - ok so it's not that you have a com add-in. It's that you have a custom form page on the message you're trying to look at. Nowadays that usually means a com add-in has added a form page, but it could also (I think) mean an old school IPM.Note.<customform> type custom form.

Lemme know what you figure out
