### ISSUE TITLE
Only works on one account at a time?

### ISSUE THREAD

**Issue by lseltzer** [microsoft/MHA#243]
I have two Office 365 accounts, one for work and one personal. I have separate Outlook windows open, one for each. I just noticed that the MHA icon is only open on one of them. I've noticed in the past that sometimes it's available, sometimes not, but I think this is the explanation.

**Comment by stephenegriffin** [comment]
Is the same true for other add-ins? MHA doesn't have any role in determining when the icon is active - that happens on Outlook's end.

**Comment by lseltzer** [comment]
Stephen,

Late last night I had to reboot for an unrelated reason and (not saying it’s necessarily because of this) since then, it shows up in both instances of outlook. On top is larry@larryseltzer.com<mailto:larry@larryseltzer.com>, on the bottom is larry.seltzer@hpe.com<mailto:larry.seltzer@hpe.com>.

[cid:image001.png@01D6C7B1.E2CBBC70]

On the other hand, there are other add-ins on one and not the other. I’ve always found management of this stuff in Outlook confusing. For instance, I would like to uninstall the Send to Slack thing, but I don’t see it anywhere in any Outlook setting.

So consider the support contact closed, it’s obviously not anything wrong with MHA. But is there a way to get a big picture on all these Outlook add-ins?

Thank you

Larry Seltzer
larry@larryseltzer.com
973.378.8728
