### ISSUE TITLE
https://mha.azurewebsites.net/ spamrules is a list without explanation 

### ISSUE THREAD

**Issue by ekelmans** [microsoft/MHA#252]
Hi,
 
Really usefull tool this, especially in combo with https://mha.azurewebsites.net/  and https://protection.office.com/quarantine

Where can i find the explanation of the spam rules line?

Spam rules | (58800400005)(8676002)(83770400001)(7596003)(86362001)(4001150100001)(1076003)(83380400001)(356005)(450100002)(6266002)(426003)(336012)(30864003)(33964004)(5660300002)(4006050)(75640400001)(33656002)(1096003)(26005)(77540400001)(51380400016)(74470400004)
-- | --

Met vriendelijke groet, 
Theo Ekelmans 
Sr. MS-SQL DBA
+31 (0) 6 2127 4593

**Comment by stephenegriffin** [comment]
That’s the sfs field from here: https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results
