### ISSUE TITLE
Outlook 2019 and error message "Failed in getCallbackTokenAsync"

### ISSUE THREAD

**Issue by Legacy777** [microsoft/MHA#253]
I am having an issue with MHA returning the error message "Failed in getCallbackTokenAsync" and no header information is displayed.  I am running Outlook 2019 as a client and have MHA installed on an on-premises Exchange 2019 Server with the latest CU.  I did not originally have this error when adding it to Exchange 2019 earlier this year.  I first probably noticed it late summer 2020.

I do not get this error if I run MHA from OWA, however upon initially logging into OWA and running MHA I get a pop up message from Chrome that says "An embedded page at appsforoffice.microsoft says:  Do you trust the domain www.mail.mydomain.com where this Office session is hosted?"  When I hit OK MHA works correctly.

Below is a screen capture of the getCallbackTokenAsync error and the diagnostics information from Outlook/MHA.  If there is any additional information you'd like or troubleshooting I can perform please let me know.

Josh

User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363
Requirement set = 1.9
ui = new
Last Update = Wed, 28 Oct 2020 18:51:59 GMT
mhaVersion = 99e621a2
contentLanguage = en-US
displayLanguage = en-US
hostname = Outlook
hostVersion = 16.0.13426.20404
permissionLevel = 3
canUseRest = true
sufficientPermission = true
origin = https://mha.azurewebsites.net
path = /pages/parentframe.html
API used = Not set
itemId = true
itemType = message
itemClass = IPM.Note
ERROR: Failed in getCallbackTokenAsync : Object doesn't support property or method 'jwt_decode'
getHeaders (https://mha.azurewebsites.net/Scripts/99e621a2/GetHeadersRest.js:70:12)
Office.context.mailbox.getCallbackTokenAsync (https://mha.azurewebsites.net/Scripts/99e621a2/GetHeadersRest.js:123:20)
Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.debug.js:7893:9)
Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.debug.js:7634:7)
agaveResponseCallback (:1:7161)
window.agaveHostCallback (:1:9626)

![MHA Error](https://user-images.githubusercontent.com/29744304/103449898-4d326e00-4c74-11eb-94f0-aa2e4a2f186e.JPG)

**Comment by knightian** [comment]
Exact same issue for me

**Comment by Legacy777** [comment]
As an update, I checked this recently and it appears to be fixed via an update to MHA.  The version went from 99e621a2 to 15cbcd3b5.

Thanks!
Josh

Diagnostics
User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19042
Requirement set = 1.9
ui = new
Last Update = Sun, 25 Apr 2021 03:09:27 GMT
mhaVersion = 15cbcd3b5
contentLanguage = en-US
displayLanguage = en-US
hostname = Outlook
hostVersion = 16.0.13901.20462
permissionLevel = 3
canUseRest = true
sufficientPermission = true
origin = https://mha.azurewebsites.net
path = /pages/parentframe.html
API used = EWS
itemId = true
itemType = message
itemClass = IPM.Note
