### ISSUE TITLE
[Feature-Request] Show Header in Column

### ISSUE THREAD

**Issue by SnejPro** [microsoft/MHA#271]
Hi,

i'd like to visualize whether a mail comes from inside or outside our organization based on the headers our mail gateway adds to the mails. I think this would be a good way to prevent phising attacks.

One way to achive this is to show these specific headers as column in the mailbox. 

It would be great if you could implement this.

**Comment by stephenegriffin** [comment]
Is there a particular header you're wanting to expose? and in which table do you want to see it?

**Comment by SnejPro** [comment]
> 
> 
> Is there a particular header you're wanting to expose? and in which table do you want to see it?

I want to choose the header(s) Outlook should show. In my case there are special headers my mail gateway adds.

Here's an example:
![Unbenannt](https://user-images.githubusercontent.com/11321022/112726481-01632e00-8f1e-11eb-8918-5fcd2f58ac44.PNG)

**Comment by stephenegriffin** [comment]
It sounds like you're asking for MHA to reach into the Outlook UI and modify the columns Outlook shows. This would not be possible.
