### ISSUE TITLE
email hop times in Outlook on IOS devices

### ISSUE THREAD

**Issue by iiitee** [microsoft/MHA#321]
In outlook on IOS, when I view the received tab all the initial time always starts at 12:00am.  The time between hops seems to accurate (eg. 1 sec or 30 seconds) but it always shows the start time at 12:00am and the times at the top of each hop are 12:00am

This is with the latest version of IOS 15.1 and outlook for IOS 4.2143.0 but it has been happening in prior versions as well

**Comment by stephenegriffin** [comment]
I think I repro this...thanks for the report

**Comment by iiitee** [comment]
sure, let me know if you need any more information or testing
