### ISSUE TITLE
MHA not working -  Access to ODATA is disabled

### ISSUE THREAD

**Issue by nimchak** [microsoft/MHA#49]
First and foremost this is a great product.  Thank you for working tirelessly on it.

We are using O365 Gov cloud and I know REST has been disabled there.  Also we do EWS filtering and our allow list consist of the following agents.
 -EwsAllowList "Outlook-Android/*","Outlook-iOS/*","ExchangeService
sClient/*","*outlook*","*MAPI*","*skype*","Microsoft+Office/*","UCCAPI/*","OC/*","OCPhone/*","Microsoft Office/*","MacOu
tlook/*"

Could either of these issues be the cause of why MHA is not working for us.   Any ideas?

We get the following when we click the MHA icon on an email within Outlook.
textStatus: error errorThrown: State: rejected jqXHR: { "readyState": 4, "responseText": "{\"error\":{\"code\":\"ErrorAccessDenied\",\"message\":\"Access to OData is disabled.\"}}", "responseJSON": { "error": { "code": "ErrorAccessDenied", "message": "Access to OData is disabled." } }, "status": 403, "statusText": "error" }

**Comment by stephenegriffin** [comment]
This might be the same issue as #38, which I now think was caused by moving the rest/ews calls into a frame. I'm working on pulling them back out and leaving the frames to just to rendering, which should fix #38, and then we'll see if it fixes this.

BTW - this didn't happen to be working at the start of the year did it?

**Comment by nimchak** [comment]
Stephen,
We found the solution.  If you are doing EWS filtering as we are you need to include "Mozilla/*" in the list.  I basically kicked off fiddler and attempted to use MHA and noticed that the user agent was "Mozilla/...".  After adding that by performing the following powershell statement it all started working.  Thanks for your help.

set-organizationconfig -ewsallowlist "Outlook-Android/\*","Outlook-iOS/\*","ExchangeServicesClient
/\*","\*outlook\*","\*MAPI\*","\*skype\*","Microsoft+Office/\*","UCCAPI/*","OC/\*","OCPhone/\*","Microsoft Office/\*","MacOutlook/\*","Mozilla/\*"

**Comment by stephenegriffin** [comment]
Good find - I'm reporting this to the devs - this is non-obvious...

**Comment by stephenegriffin** [comment]
Hey - can you give me more details on the frame that failed for you? Perhaps send me the fiddle? You can DM me @ my twitter: https://twitter.com/sgriffin
