### ISSUE TITLE
Error: Cannot parse given Error object

### ISSUE THREAD

**Issue by stephenegriffin** [microsoft/MHA#51]
Reported in comments of #38 by @Vierxa and #37 by @luisjmoreno.

From @Vierxa 
User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Requirement set = 1.5
hostname = OutlookWebApp
hostVersion = 15.1.1415.2
OWAView = ThreeColumns
itemType = message
itemClass = IPM.Note
contentLanguage = 
displayLanguage = fr-FR
touchEnabled = false
ERROR: Cannot parse given Error object
OK

From @luisjmoreno
----- ------- --Firefox on Windows
User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Requirement set = 1.3
hostname = OutlookWebApp
hostVersion = 15.0.1347.5
OWAView = ThreeColumns
itemType = message
itemClass = IPM.Note
contentLanguage =
displayLanguage = en-US
touchEnabled = undefined
ERROR: Cannot parse given Error object
parse@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:1:1299
fromError/<@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:2:14676
fromError@https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/2.0.0/stacktrace-with-promises-and-json-polyfills.min.js:2:14644
LogError@https://mha.azurewebsites.net/Scripts/uiToggle.js:117:9
ShowError@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:5
callbackEWS@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:60:9
sendHeadersRequestEWS/<@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:18:13
makeEwsRequestAsync/i.onreadystatechange@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:5497
$2P_1@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:55509
$m_1/<@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlookwebapp-15.01.js:17:59912

**Comment by stephenegriffin** [comment]
I suspect someone threw a string, which stacktrace.js doesn't handle. I've augmented our log parsing to hopefully handle this so we can get the real error and stack logged. Hopefully "Cannot parse given Error object" will disappear, and a new error will show up in it's place. I'll need the new diagnostic output from that.

**Comment by Vierxa** [comment]
Hi Stephen,

Many thanks for the time spent debugging.
Please find below the new diagnostic

Regards,

Vierxa

```
User Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Requirement set = 1.5
hostname = OutlookWebApp
hostVersion = 15.1.1415.2
OWAView = ThreeColumns
itemType = message
itemClass = IPM.Note
contentLanguage = 
displayLanguage = fr-FR
touchEnabled = false
ERROR: Failed to make a request via HttpWebRequest. Exception: The underlying connection was closed: An unexpected error occurred on a send.
ERROR: Failed to make a request via HttpWebRequest. Exception: The underlying connection was closed: An unexpected error occurred on a send.
ERROR: ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:93:5
callbackEWS()@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:60:9
r.CommonParameters._callback$p$0()@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:18:13
r.EwsRequest.t.onreadystatechange()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:211960
r.EwsRequest._callOnReadyStateChangeCallback$i$1()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:311424
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:319266
ERROR: ShowError()@https://mha.azurewebsites.net/Scripts/uiToggle.js:95:9
callbackEWS()@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:60:9
r.CommonParameters._callback$p$0()@https://mha.azurewebsites.net/Scripts/GetHeadersEWS.js:18:13
r.EwsRequest.t.onreadystatechange()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:211960
r.EwsRequest._callOnReadyStateChangeCallback$i$1()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:311424
{anonymous}()@https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:13:319266
```

**Comment by stephenegriffin** [comment]
Can I get a fiddler of this? You can DM me through twitter (@sgriffin) to arrange the file transfer.

**Comment by Vierxa** [comment]
Stephen,

Did you change something?
It works perfectly now !!!

**Comment by Vierxa** [comment]
Stephen,

I found the cause of my problem.
We use a Haproxy server to connect to our webmail.
It was too secure prohibiting the tls 1.0.
By reactivating the Tls1.0, MHA works perfectly.

**Comment by stephenegriffin** [comment]
That's good info - I think maybe I can pass a header to avoid needing tls 1.0...I'll need to do some research

**Comment by stephenegriffin** [comment]
Pretty sure error parsing work has fixed or drastically changed this one.
