### ISSUE TITLE
Please specify which browser version is supported

### ISSUE THREAD

**Issue by rafalfitt** [microsoft/MHA#88]
I have a suspicion that MSIE might be required :-(

**Comment by stephenegriffin** [comment]
Add-ins don't control the requirements. Outlook does use IE to host all web-addins. but OWA runs on just about anything.

Could you expand on the issue you're experiencing that leads you to ask this?

**Comment by rafalfitt** [comment]
We are slowly getting rid of good old MSIE (removing from computers) and MHA in Outlook 2016 stopped working :-(

**Comment by stephenegriffin** [comment]
Ah - well - all your other add-ins are gonna stop working too. So, to be clear: MHA has no dependency on IE. But Office does have a dependency on IE for add-ins.

**Comment by rafalfitt** [comment]
Thx for clarification
