### ISSUE TITLE
MHA 3.1 does not work on iOS and Safari on Mac OS

### ISSUE THREAD

**Issue by EinmalIM** [microsoft/MHA#97]
Some of the last iOS and MacOS updates - not sure which - made MHA stop working.

I use MHA 3.1 without problems in OWA on Windows Browsers and Outlook but on iOS and Safari for MacOS 10.13.5 it stays blank.

My mailbox is running on our On-Prem Exchange 2016. I see 15.1.1468.8 in OWA sources.

We have the same problem with an Add-In we developed. Any ideas if that can be fixed in the Add-In code or is that a browser bug on Mac?

**Comment by EinmalIM** [comment]
Any updates on this one?

This is a big issue for us, as we advertised our Office Mail-Addin to be our integration point for MacOS and iOS users. Luckily it is still working in Outlook for MacOS - but browser based Apple access is currently gone...

The JavaScript console on Safari is full with these errors that js files cannot be loaded as CSS files - which seems reasonable. So maybe some resource loading logic in OWA should be fixed?

_Did not parse stylesheet at 'https://our-server/owa/prem/15.1.1466.8/scripts/de/microsoft.exchange.clients.owa2.client.calpeekstrings.localized.min.js' because non CSS MIME types are not allowed in strict mode._

**Comment by stephenegriffin** [comment]
I don't have a mac to test this on, but MHA appears to work for me on iOS in Safari. If there is an issue here, it sounds like it's in OWA.

**Comment by drvespa** [comment]
Hi EinmalIM, what version of macOS are you using? Also, what version of Safari are you using?

**Comment by EinmalIM** [comment]
@stephenegriffin: rechecked: are you using MHA in an Office 365 mailbox? In O365 MHA works for me, but not in our On-Prem Exchange 2016.

@drvespa: MacOS 10.13.6 with Safari 11.1.2

In addition I tried an iPad with iOS 11.4.1:
- Native Safari browser does not show the HTML UI of MHA or our Addin.
- Using Outlook for iPad the HTML UI is rendered. Seems that pure Safari is more picky about the HTML content
- Same with Outlook on Mac which renders the Addins UI as well
