### ISSUE TITLE
Feature Request: Message encryption

### ISSUE THREAD

**Issue by krasian-zz** [microsoft/MHA#98]
On the Received tab/section, it would be nice to see if encryption is used, and if so, the type of encryption.  Currently, I look at message headers, and then track each hop along with the type of encryption.  It would be nice if your addon could do that automatically.

**Comment by stephenegriffin** [comment]
can you give examples of which headers you look at and what you look for in them?

**Comment by krasian-zz** [comment]
Even better...this is how I would envision some sort of implementation...

This is how it is now...
![image](https://user-images.githubusercontent.com/26934540/45054207-4ec6d980-b05a-11e8-8956-3128b0ea832f.png)

This is how I would envision its implementation...
![image](https://user-images.githubusercontent.com/26934540/45054237-60a87c80-b05a-11e8-957f-d09a30a74c2b.png)

**Comment by stephenegriffin** [comment]
Examples of headers you look at and what you look for in them would be better for writing code...

**Comment by krasian-zz** [comment]
Here's some.

![image](https://user-images.githubusercontent.com/26934540/45097788-9d738280-b0f1-11e8-87b6-6d186edb88ff.png)

This one shows TLS v1
![image](https://user-images.githubusercontent.com/26934540/45097889-dad81000-b0f1-11e8-9fbf-e633e125dc4b.png)

This is just for transport level encryption.  Showing end-to-end (PGP/GPG/MIME) would be nice too!

**Comment by stephenegriffin** [comment]
Finally looking at this.
In classic view, what you're asking for appears to already be in the Type column:
![image](https://user-images.githubusercontent.com/6773183/87710121-58035000-c773-11ea-947a-d03f0c17f74f.png)
In New, it's in the popup when you tap a row:
![image](https://user-images.githubusercontent.com/6773183/87710236-7c5f2c80-c773-11ea-8bbf-8028029359cc.png)
And same in new-mobile:
![image](https://user-images.githubusercontent.com/6773183/87710309-9ac52800-c773-11ea-8bce-e3436c9d2726.png)

I suppose I could look at exposing the information in a different manner, but I'm not sure exactly what that would look like.
